[pytest]
testpaths = tests
addopts = -ra --strict-markers --html=reports/report.html --self-contained-html
cache_dir = reports/.pytest_cache
markers =
    ui: UI automation tests that run in a browser.
    api: API tests that run with HTTP requests.
